package com.yaorange.service.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.13
 * 2020-06-24T10:36:39.647+08:00
 * Generated source version: 3.2.13
 *
 */
@WebServiceClient(name = "WSInterfaceService",
                  wsdlLocation = "http://127.0.0.1:1234/hello?wsdl",
                  targetNamespace = "http://service.cxf.yaorange.com/")
public class WSInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxf.yaorange.com/", "WSInterfaceService");
    public final static QName WSInterfacePort = new QName("http://service.cxf.yaorange.com/", "WSInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:1234/hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:1234/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WSInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WSInterfacePort")
    public WSInterface getWSInterfacePort() {
        return super.getPort(WSInterfacePort, WSInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WSInterfacePort")
    public WSInterface getWSInterfacePort(WebServiceFeature... features) {
        return super.getPort(WSInterfacePort, WSInterface.class, features);
    }

}
