package com.yaorange.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.13
 * 2020-06-24T11:35:57.038+08:00
 * Generated source version: 3.2.13
 *
 */
@WebService(targetNamespace = "http://service.ws.yaorange.com/", name = "MyWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface MyWebService {

    @WebMethod
    @RequestWrapper(localName = "helloworld", targetNamespace = "http://service.ws.yaorange.com/", className = "com.yaorange.ws.Helloworld")
    @ResponseWrapper(localName = "helloworldResponse", targetNamespace = "http://service.ws.yaorange.com/", className = "com.yaorange.ws.HelloworldResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String helloworld(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
